add pure25519 doc requirement (#2)
The pure25519 dependency is missing from the python requirements,
so the quickstart doesn't quite build, it fails like this:

```
.\bao_flash.bat build blink
Using RISC-V toolchain from PATH.

============================================
============================================

[1/4] Assembling startup ...
[2/4] Compiling SDK ...
[3/4] Compiling blink ...
[4/4] Linking blink.uf2 ...
Traceback (most recent call last):
  File "F:\code\dabao-sdk\tools\sign_and_uf2.py", line 40, in <module>
    from pure25519.basic import bytes_to_clamped_scalar, scalar_to_bytes, Base
ModuleNotFoundError: No module named 'pure25519'

*** FAILED ***
```

Adding the requirement fixes this issue.